# Generated by Django 2.2 on 2020-12-25 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lodge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('rent_start_date', models.DateField(blank=True, null=True)),
                ('rent_end_date', models.DateField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('terms_agreed', models.BooleanField(default=False)),
                ('verified', models.CharField(default='unverified', max_length=20)),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('amount_settled', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('payment_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_plan', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('app_fee', models.IntegerField(blank=True, null=True)),
                ('merchant_fee', models.IntegerField(blank=True, null=True)),
                ('manual_pay', models.BooleanField(default=False)),
                ('lodge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lodge.Lodge')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lodge.Room')),
            ],
        ),
    ]
