# Generated by Django 2.2 on 2020-12-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payments_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
