# Generated by Django 2.2 on 2020-12-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20201231_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='manual_pay',
            field=models.BooleanField(default=False),
        ),
    ]
