# Generated by Django 2.2 on 2021-01-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20210102_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='lodge_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
