# Generated by Django 2.2 on 2020-12-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20201207_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='charge_response_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
