# Generated by Django 2.2 on 2020-12-08 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0009_auto_20201204_1521'),
        ('payments', '0008_payment_charge_response_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='lodge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lodge.Lodge'),
        ),
        migrations.AddField(
            model_name='payment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lodge.Room'),
        ),
    ]
