# Generated by Django 2.2 on 2020-12-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20201208_0723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payments_type',
            new_name='payment_type',
        ),
    ]
