# Generated by Django 2.2 on 2020-12-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20201208_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='verified',
            field=models.CharField(default='unverified', max_length=20),
        ),
    ]
