# Generated by Django 2.2 on 2020-12-08 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_payment_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='charge_response_code',
            new_name='currency',
        ),
    ]
