# Generated by Django 2.2 on 2020-12-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_auto_20201208_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='update_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_settled',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
