# Generated by Django 2.2 on 2020-12-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_auto_20201208_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='manual_pay',
            field=models.BooleanField(default=False),
        ),
    ]
