# Generated by Django 2.2 on 2020-05-25 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lodge.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lodge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=80)),
                ('image', models.ImageField(null=True, upload_to=lodge.models.image_file_path)),
                ('water', models.BooleanField(blank=True, null=True)),
                ('electricity', models.BooleanField(blank=True, null=True)),
                ('num_of_rooms', models.PositiveSmallIntegerField()),
                ('amenities', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.PositiveSmallIntegerField()),
                ('floor', models.IntegerField(default=0)),
                ('occupied', models.BooleanField()),
                ('lodge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='lodge.Lodge')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('room_number',),
            },
        ),
    ]
