# Generated by Django 2.2 on 2020-12-01 11:42

from django.db import migrations, models
import django.db.models.deletion
import lodge.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lodge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=80)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=lodge.models.image_file_path)),
                ('water', models.BooleanField(blank=True, null=True)),
                ('electricity', models.BooleanField(blank=True, null=True)),
                ('num_of_rooms', models.PositiveSmallIntegerField()),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.CharField(blank=True, default='omiax', max_length=100, null=True)),
                ('standard_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('agreement', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.PositiveSmallIntegerField()),
                ('floor', models.IntegerField(default=0)),
                ('occupied', models.BooleanField(default=False)),
                ('room_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('room_mates', models.CharField(blank=True, max_length=255, null=True)),
                ('rent_start_date', models.DateField(blank=True, null=True)),
                ('rent_end_date', models.DateField(blank=True, null=True)),
                ('transaction_id', models.PositiveIntegerField(blank=True, null=True)),
                ('terms_agreed', models.BooleanField(default=False)),
                ('lodge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='lodge.Lodge')),
            ],
            options={
                'ordering': ('lodge', 'room_number'),
            },
        ),
    ]
