# Generated by Django 2.2 on 2020-12-25 17:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import lodge.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lodge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('', ''), ('Abia', 'Abia'), ('Abuja (FCT)', 'Abuja (FCT)'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara')], max_length=80)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=lodge.models.image_file_path)),
                ('water', models.BooleanField(blank=True, null=True)),
                ('electricity', models.BooleanField(blank=True, null=True)),
                ('num_of_rooms', models.PositiveSmallIntegerField()),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.CharField(blank=True, default='omiax', max_length=100, null=True)),
                ('standard_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('caution_deposit', models.IntegerField(blank=True, default=3, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('agreement', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.PositiveSmallIntegerField()),
                ('floor', models.IntegerField(default=0)),
                ('occupied', models.BooleanField(default=False)),
                ('room_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('room_mates', models.CharField(blank=True, max_length=255, null=True)),
                ('rent_start_date', models.DateField(blank=True, null=True)),
                ('rent_end_date', models.DateField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('terms_agreed', models.BooleanField(default=False)),
                ('lodge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='lodge.Lodge')),
            ],
            options={
                'ordering': ('lodge', 'room_number'),
            },
        ),
    ]
