# Generated by Django 2.2 on 2020-05-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lodge',
            old_name='amenities',
            new_name='details',
        ),
        migrations.AddField(
            model_name='lodge',
            name='country',
            field=models.CharField(default='Nigeria', max_length=100),
        ),
    ]
