# Generated by Django 2.2 on 2020-12-01 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0002_auto_20201201_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='tenant',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
