# Generated by Django 2.2 on 2020-05-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0002_auto_20200525_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
    ]
