# Generated by Django 2.2 on 2020-12-31 13:01

from django.db import migrations, models
import django.db.models.deletion
import lodge.models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0002_auto_20201225_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodge',
            name='image',
        ),
        migrations.CreateModel(
            name='LodgeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictures', models.ImageField(blank=True, null=True, upload_to=lodge.models.image_file_path)),
                ('lodge', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lodge_image', to='lodge.Lodge')),
            ],
        ),
    ]
