# Generated by Django 2.2 on 2020-05-25 18:08

from django.db import migrations, models
import lodge.models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0003_auto_20200525_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=lodge.models.image_file_path),
        ),
    ]
