# Generated by Django 2.2 on 2021-01-01 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0003_auto_20201231_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgeimage',
            name='lodge',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lodge_images', to='lodge.Lodge'),
        ),
    ]
