# Generated by Django 2.2 on 2020-06-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0004_auto_20200525_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodge',
            name='standard_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='room',
            name='room_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
