# Generated by Django 2.2 on 2021-01-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0004_auto_20210101_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodge',
            name='fencing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lodge',
            name='tar_road',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
