# Generated by Django 2.2 on 2021-01-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0005_auto_20210114_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lodge',
            old_name='num_of_rooms',
            new_name='num_of_flats',
        ),
        migrations.AlterField(
            model_name='lodge',
            name='caution_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
