# Generated by Django 2.2 on 2020-12-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0007_auto_20201204_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
