# Generated by Django 2.2 on 2020-12-04 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0008_auto_20201204_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodge',
            name='caution_deposit',
            field=models.IntegerField(blank=True, default=3, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
