# Generated by Django 2.2 on 2020-06-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0008_auto_20200608_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_mates',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
