# Generated by Django 2.2 on 2020-12-10 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0009_auto_20201204_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='tenant',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to=settings.AUTH_USER_MODEL),
        ),
    ]
