# Generated by Django 2.2 on 2020-06-09 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0009_room_room_mates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('lodge', 'room_number')},
        ),
    ]
