# Generated by Django 2.2 on 2020-06-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0010_auto_20200609_2231'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('lodge', 'room_number')},
        ),
    ]
