# Generated by Django 2.2 on 2020-06-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0011_auto_20200612_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodge',
            name='owner',
            field=models.CharField(blank=True, default='omiax', max_length=100, null=True),
        ),
    ]
