# Generated by Django 2.2 on 2020-09-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0012_lodge_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rent_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='rent_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
