# Generated by Django 2.2 on 2020-09-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0013_auto_20200913_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='transaction_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
