# Generated by Django 2.2 on 2020-06-08 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0007_auto_20200608_1932'),
        ('user', '0003_auto_20200604_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='occupant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupants', to='lodge.Room'),
        ),
    ]
