# Generated by Django 2.2 on 2021-01-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210114_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankinfo',
            name='account_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
