# Generated by Django 2.2 on 2020-06-08 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_occupant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='occupant',
        ),
    ]
