# Generated by Django 2.2 on 2020-11-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201124_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyinfo',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
