# Generated by Django 2.2 on 2020-11-25 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20201124_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyinfo',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency', to=settings.AUTH_USER_MODEL),
        ),
    ]
